### ISSUE TITLE
Couldn't find VCPKG_ROOT, also can't fallback to homebrew because it's only for macos aarch64. [scrap 0.5.0] stack backtrace:

### ISSUE THREAD

**Issue by Martinfx** [quadrupleslap/scrap#50]
Hi,
i have problem with package on FreeBSD I have enable CARGO_FEATURES+=linux-pkg-config

```
     Running `CARGO=/usr/local/bin/cargo CARGO_CFG_PANIC=unwind CARGO_CFG_TARGET_ABI='' CARGO_CFG_TARGET_ARCH=x86_64 CARGO_CFG_TARGET_ENDIAN=little CARGO_CFG_TARGET_ENV='' CARGO_CFG_TARGET_FAMILY=unix CARGO_CFG_TARGET_FEATURE=fxsr,sse,sse2 CARGO_CFG_TARGET_HAS_ATOMIC=16,32,64,8,ptr CARGO_CFG_TARGET_OS=freebsd CARGO_CFG_TARGET_POINTER_WIDTH=64 CARGO_CFG_TARGET_VENDOR=unknown CARGO_CFG_UNIX='' CARGO_ENCODED_RUSTFLAGS='-Clink-arg=-fstack-protector-strong' CARGO_FEATURE_DBUS=1 CARGO_FEATURE_GSTREAMER=1 CARGO_FEATURE_GSTREAMER_APP=1 CARGO_FEATURE_GSTREAMER_VIDEO=1 CARGO_FEATURE_LINUX_PKG_CONFIG=1 CARGO_FEATURE_TRACING=1 CARGO_FEATURE_WAYLAND=1 CARGO_MANIFEST_DIR=/usr/home/maxfx/Documents/FreeBSD-Ports/rustdesk/work/rustdesk-d2f119b/libs/scrap CARGO_PKG_AUTHORS='Ram <quadrupleslap@gmail.com>' CARGO_PKG_DESCRIPTION='Screen capture made easy.' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=scrap CARGO_PKG_README=README.md CARGO_PKG_REPOSITORY='https://github.com/quadrupleslap/scrap' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.5.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=5 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' DEBUG=true HOST=x86_64-unknown-freebsd LD_LIBRARY_PATH='/usr/home/maxfx/Documents/FreeBSD-Ports/rustdesk/work/target/debug/deps:/usr/home/maxfx/Documents/FreeBSD-Ports/rustdesk/work/target/debug:/usr/local/lib/rustlib/x86_64-unknown-freebsd/lib' NUM_JOBS=1 OPT_LEVEL=0 OUT_DIR=/usr/home/maxfx/Documents/FreeBSD-Ports/rustdesk/work/target/x86_64-unknown-freebsd/debug/build/scrap-6b65a80b9b92cc3d/out PROFILE=debug RUSTC=/usr/local/bin/rustc RUSTC_LINKER=clang18 RUSTDOC=/usr/local/bin/rustdoc TARGET=x86_64-unknown-freebsd /usr/home/maxfx/Documents/FreeBSD-Ports/rustdesk/work/target/debug/build/scrap-5cc50700b0602c59/build-script-build`
[scrap 0.5.0] cargo:rerun-if-env-changed=NO_PKG_CONFIG_libyuv
[scrap 0.5.0] thread 'main' panicked at libs/scrap/build.rs:84:9:
[scrap 0.5.0] Couldn't find VCPKG_ROOT, also can't fallback to homebrew because it's only for macos aarch64.
[scrap 0.5.0] stack backtrace:
[scrap 0.5.0]    0: std::panicking::begin_panic
[scrap 0.5.0]              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:686:12
[scrap 0.5.0]    1: build_script_build::link_homebrew_m1
[scrap 0.5.0]              at ./build.rs:84:9
[scrap 0.5.0]    2: build_script_build::find_package
[scrap 0.5.0]              at ./build.rs:144:14
[scrap 0.5.0]    3: build_script_build::main
[scrap 0.5.0]              at ./build.rs:203:5
[scrap 0.5.0]    4: core::ops::function::FnOnce::call_once
[scrap 0.5.0]              at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
[scrap 0.5.0] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `scrap v0.5.0 (/usr/home/maxfx/Documents/FreeBSD-Ports/rustdesk/work/rustdesk-d2f119b/libs/scrap)`


```

**Comment by rixcian** [comment]
You need to install `vcpkg`: https://github.com/microsoft/vcpkg?tab=readme-ov-file#quick-start-unix

And then set the `VCPKG_ROOT` environment variable pointing to the `vcpkg` installation folder.
