### ISSUE TITLE
ConnectionRefused

### ISSUE THREAD

**Issue by DGolubets** [quadrupleslap/scrap#7]
Hi,
I get an error on Windows 10: Couldn't capture frame.: Error { repr: Kind(ConnectionRefused) }.

**Comment by quadrupleslap** [comment]
See issue #2. I'll try adding a patch for this today, but the problem is that I don't have a computer that I can test this on (only a Windows virtual machine), so it'll just be stabbing in the dark.

**Comment by quadrupleslap** [comment]
Should be fixed!

**Comment by DGolubets** [comment]
Yep, it works now! Thanks.

**Comment by samarthc-rapid** [comment]
Hi, I am getting this error on windows 10 

```
     Running `target\debug\screenshot.exe`
thread 'main' panicked at 'Couldn't begin capture.: Kind(ConnectionRefused)', src\main.rs:15:47
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584        
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143       
   2: core::result::unwrap_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\result.rs:1785
   3: enum$<core::result::Result<scrap::common::dxgi::Capturer,std::io::error::Error> >::expect<scrap::common::dxgi::Capturer,std::io::error::Error>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\result.rs:1035
   4: screenshot::main
             at .\src\main.rs:15
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ops\function.rs:227     
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\screenshot.exe` (exit code: 101)
```
